#index:
#    path: /
#    controller: App\Controller\DefaultController::index
connect_discord_check:
  path: /connect/discord/check
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController