#index:
#    path: /
#    controller: App\Controller\DefaultController::index
connect_discord_check:
   path: /oauth/check/discord
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController